# ---- Base image ------------------------------------------------------------
FROM ipfs/go-ipfs:latest

# ---- Add custom config ----------------------------------------------------
COPY config/ipfs-config.json /data/ipfs/config

# ---- Entrypoint ------------------------------------------------------------
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]