FROM ipfs/go-ipfs:latest
COPY config/ipfs-config.json /data/ipfs/config
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]